"""add alert service and environment

Revision ID: 145230c24152
Revises: 693c60d276ef
Create Date: 2026-08-06 23:03:30.618615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145230c24152'
down_revision: Union[str, Sequence[str], None] = '693c60d276ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('service', sa.String(length=255), nullable=True))
    op.add_column('alerts', sa.Column('environment', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'environment')
    op.drop_column('alerts', 'service')
    # ### end Alembic commands ###
