"""add AI analysis fields to situations

Revision ID: 648bd6c9657e
Revises: aedeb601554b
Create Date: 2026-08-27 17:25:09.380497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648bd6c9657e'
down_revision: Union[str, Sequence[str], None] = 'aedeb601554b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('situations', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('situations', sa.Column('ai_root_cause', sa.Text(), nullable=True))
    op.add_column('situations', sa.Column('ai_recommendations', sa.Text(), nullable=True))
    op.add_column('situations', sa.Column('ai_status',sa.String(length=50),nullable=False,server_default="Pending",),)
    op.add_column('situations', sa.Column('ai_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('situations', 'ai_updated_at')
    op.drop_column('situations', 'ai_status')
    op.drop_column('situations', 'ai_recommendations')
    op.drop_column('situations', 'ai_root_cause')
    op.drop_column('situations', 'ai_summary')
    # ### end Alembic commands ###
