"""link alerts to situations

Revision ID: 693c60d276ef
Revises: ede68d0c3c6a
Create Date: 2026-08-06 22:44:34.329482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693c60d276ef'
down_revision: Union[str, Sequence[str], None] = 'ede68d0c3c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('situation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alerts', 'situations', ['situation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'situation_id')
    # ### end Alembic commands ###
