"""add situation correlation evidence

Revision ID: aedeb601554b
Revises: 145230c24152
Create Date: 2026-08-27 17:06:31.706539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aedeb601554b'
down_revision: Union[str, Sequence[str], None] = '145230c24152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('situations', sa.Column('correlation_score', sa.Float(), nullable=True))
    op.add_column('situations', sa.Column('correlation_method', sa.String(length=100), nullable=True))
    op.add_column('situations', sa.Column('correlation_reasons', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('situations', 'correlation_reasons')
    op.drop_column('situations', 'correlation_method')
    op.drop_column('situations', 'correlation_score')
    # ### end Alembic commands ###
